# Generated by Django 4.2 on 2026-02-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_remove_warehouse_created_at_alter_company_owner_and_more'),
        ('users', '0002_user_company_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_employees', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
