services:
  - type: web
    name: inventory-api
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: inventory-api.onrender.com

databases:
  - name: inventory-db
    plan: free
    databaseName: inventory_db
    user: inventory_user