# Generated by Django 6.0.2 on 2026-03-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_remove_product_quantity_warehouseproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
    ]
